name: web_risk_scoring_mobile
description: Mobile client for Cyber Risk Scoring System
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.1.8
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
